---
services:
  netbootxyz:
    hostname: netbootxyz
    domainname: ${LOCAL_DOMAIN}
    container_name: netbootxyz
    image: ghcr.io/netbootxyz/netbootxyz
    restart: unless-stopped
    environment:
      - MENU_VERSION=2.0.84  # optional
      - NGINX_PORT=80  # optional
      - WEB_APP_PORT=3000  # optional
    volumes:
      - conf:/config  # optional
      - assets:/assets  # optional
    dns:
      - ${NS1_IP}
      - ${NS2_IP}
    dns_search: ${LOCAL_DOMAIN}
    networks:
      net1:
        ipv4_address: ${THIS_IP}

volumes:
  conf:
  assets:

networks:
  net1:
    external: true
    name: ${LAN_NAME}
